import { CalendarIcon, DocumentIcon, EyeIcon, UploadIcon } from "./ResumeIcons";
import type { Resume } from "./types";

export default function CurrentResumeCard({ resume }: { resume: Resume }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600">Current resume</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Your active interview profile</h2></div>
    <div className="p-6"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 text-white shadow-md shadow-indigo-200"><DocumentIcon className="size-7" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-lg font-semibold text-slate-950">{resume.title}</h3><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{resume.status}</span></div><p className="mt-1 text-sm font-medium text-slate-600">Target role: {resume.targetRole}</p><p className="mt-3 flex items-center gap-1.5 text-xs text-slate-500"><CalendarIcon className="size-4" /> Uploaded {resume.uploadedAt}</p></div></div><div className="flex items-center gap-3 rounded-2xl bg-slate-50 px-4 py-3 sm:text-right"><div><p className="text-xs font-medium text-slate-500">Resume score</p><p className="text-2xl font-semibold text-slate-950">{resume.score}<span className="text-sm text-slate-400">/100</span></p></div><div className="grid size-12 place-items-center rounded-full border-4 border-indigo-500 bg-white text-xs font-bold text-indigo-700">{resume.score}%</div></div></div>
      <div className="mt-6 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:flex-wrap"><button type="button" className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"><EyeIcon className="size-4" /> View Analysis</button><button type="button" className="rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-semibold text-indigo-700 hover:bg-indigo-100">Use for Interview</button><button type="button" className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-indigo-200 hover:bg-indigo-50"><UploadIcon className="size-4" /> Replace Resume</button></div>
    </div>
  </section>;
}
