import { BriefcaseIcon, CalendarIcon, LocationIcon } from "./JobIcons";
import type { Opportunity } from "./types";

export default function CurrentOpportunityCard({ opportunity }: { opportunity: Opportunity }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600">Current opportunity</p><h2 className="mt-1 text-lg font-semibold text-slate-950">Your active target role</h2></div><div className="p-6">
    <div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div className="flex min-w-0 gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 text-white shadow-md shadow-indigo-200"><BriefcaseIcon className="size-7" /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold text-slate-950">{opportunity.title}</h3><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{opportunity.status}</span></div><p className="mt-1 text-sm font-semibold text-slate-600">{opportunity.company}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500"><span className="flex items-center gap-1.5"><LocationIcon className="size-4" />{opportunity.location}</span><span>{opportunity.employmentType}</span><span className="flex items-center gap-1.5"><CalendarIcon className="size-4" />Added {opportunity.dateAdded}</span></div></div></div><div className="rounded-2xl bg-slate-50 px-5 py-3 text-center"><p className="text-xs font-medium text-slate-500">Resume match</p><p className="mt-1 text-3xl font-semibold text-indigo-700">{opportunity.matchScore}%</p></div></div>
    <div className="mt-6 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:flex-wrap"><button type="button" className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">View Analysis</button><button type="button" className="rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2.5 text-sm font-semibold text-indigo-700 hover:bg-indigo-100">Use for Interview</button><button type="button" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-indigo-200 hover:bg-indigo-50">Replace Job Description</button></div>
  </div></section>;
}
