import { BriefcaseIcon, CalendarIcon, EyeIcon, LocationIcon, PlusIcon, TrashIcon } from "./JobIcons";
import type { Opportunity } from "./types";

function EmptyOpportunities() {
  return <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center shadow-sm"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><BriefcaseIcon className="size-7" /></span><h3 className="mt-4 font-semibold text-slate-950">No job descriptions saved yet</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Add a job description to compare opportunities and prepare tailored interviews.</p><button type="button" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"><PlusIcon className="size-4" /> Add New Job Description</button></div>;
}

function OpportunityCard({ opportunity }: { opportunity: Opportunity }) {
  const isActive = opportunity.status === "Active";
  return <article className="flex h-full flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><BriefcaseIcon className="size-5" /></span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${isActive ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{opportunity.status}</span></div><h3 className="mt-4 text-base font-semibold text-slate-950">{opportunity.title}</h3><p className="mt-1 text-sm font-medium text-slate-600">{opportunity.company}</p><div className="mt-4 space-y-2 text-xs text-slate-500"><p className="flex items-center gap-1.5"><LocationIcon className="size-4" />{opportunity.location}</p><p className="flex items-center gap-1.5"><CalendarIcon className="size-4" />Added {opportunity.dateAdded}</p></div><div className="mt-4 flex items-center justify-between border-y border-slate-100 py-3"><span className="text-xs text-slate-500">Resume match</span><span className="text-sm font-semibold text-indigo-700">{opportunity.matchScore}%</span></div><div className="mt-auto grid grid-cols-2 gap-2 pt-5"><button type="button" className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:border-indigo-200 hover:bg-indigo-50"><EyeIcon className="size-3.5" /> View</button><button type="button" disabled={isActive} className="rounded-xl bg-indigo-600 px-3 py-2 text-xs font-semibold text-white hover:bg-indigo-700 disabled:cursor-default disabled:bg-slate-100 disabled:text-slate-400">{isActive ? "Active Role" : "Set as Active"}</button><button type="button" className="col-span-2 inline-flex items-center justify-center gap-1.5 rounded-xl px-3 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50"><TrashIcon className="size-3.5" /> Delete</button></div></article>;
}

export default function SavedOpportunitiesSection({ opportunities }: { opportunities: Opportunity[] }) {
  return <section aria-labelledby="saved-opportunities-title"><div className="mb-4"><h2 id="saved-opportunities-title" className="text-xl font-semibold tracking-tight text-slate-950">Saved Opportunities</h2><p className="mt-1 text-sm text-slate-500">Compare roles and keep your interview targets organized.</p></div>{opportunities.length > 0 ? <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{opportunities.map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} />)}</div> : <EmptyOpportunities />}</section>;
}
